<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>swift</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>Swift</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#literals</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage-type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#loop-control</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#conditional-statement</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#control-transfer-statement</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator-keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#special-keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class-function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#primitive-type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#collection-type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#boolean</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#import</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#special-literal</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>arithmetic-operator</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)(\+|\-|\*|\/)(?!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.swift</string>
		</dict>
		<key>assignment-operator</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)(\+|\-|\*|\/|%|&lt;&lt;|&gt;&gt;|&amp;|\^|\||&amp;&amp;|\|\|)?=(?!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)</string>
			<key>name</key>
			<string>keyword.operator.assignment.swift</string>
		</dict>
		<key>bitwise-operator</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)(&amp;|\||\^|&lt;&lt;|&gt;&gt;)(?!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)</string>
			<key>name</key>
			<string>keyword.operator.bitwise.swift</string>
		</dict>
		<key>block-comment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.block.begin.swift</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Block level comments</string>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.block.end.swift</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.swift</string>
		</dict>
		<key>boolean</key>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>keyword.constant.boolean.swift</string>
		</dict>
		<key>class-function</key>
		<dict>
			<key>match</key>
			<string>\b(init|get|set|willSet|didSet|override)</string>
			<key>name</key>
			<string>keyword.swift</string>
		</dict>
		<key>collection-type</key>
		<dict>
			<key>comment</key>
			<string>Collection types</string>
			<key>match</key>
			<string>\b(Array|Dictionary)\b</string>
			<key>name</key>
			<string>storage.type.swift</string>
		</dict>
		<key>comments</key>
		<dict>
			<key>comment</key>
			<string>All comment types</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#documentation-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#in-line-comment</string>
				</dict>
			</array>
		</dict>
		<key>comparative-operator</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)((=|!)==?|(&lt;|&gt;)=?|~=)(?!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)</string>
			<key>name</key>
			<string>keyword.operator.comparative.swift</string>
		</dict>
		<key>conditional-statement</key>
		<dict>
			<key>name</key>
			<string>keyword.control.conditional.swift</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#if-else-statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#switch-statement</string>
				</dict>
			</array>
		</dict>
		<key>control-transfer-statement</key>
		<dict>
			<key>match</key>
			<string>\b(continue|break|fallthrough|return)\b</string>
			<key>name</key>
			<string>keyword.control.transfer.swift</string>
		</dict>
		<key>custom-operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=[\s(\[{,;:])(\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)++(?![\s)\]},;:])</string>
					<key>name</key>
					<string>keyword.operator.custom.prefix.unary.swift</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![\s(\[{,;:])(\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)++(?![\s)\]},;:\.])</string>
					<key>name</key>
					<string>keyword.operator.custom.postfix.unary.swift</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=[\s(\[{,;:])(\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)++(?=[\s)\]},;:])</string>
					<key>name</key>
					<string>keyword.operator.custom.binary.swift</string>
				</dict>
			</array>
		</dict>
		<key>documentation-comment</key>
		<dict>
			<key>begin</key>
			<string>/\*\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.block.documentation.begin.swift</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Documentation comments</string>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.block.documentation.end.swift</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.documentation.swift</string>
		</dict>
		<key>if-else-statement</key>
		<dict>
			<key>match</key>
			<string>\b(if|else)\b</string>
			<key>name</key>
			<string>keyword.control.conditional.swift</string>
		</dict>
		<key>import</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.other.import.swift</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>support.type.module.import.swift</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Import statement</string>
			<key>match</key>
			<string>\b(import)\s+(\w+)</string>
			<key>name</key>
			<string>meta.import.swift</string>
		</dict>
		<key>in-line-comment</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.line.double-slash.swift</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>In-line comments</string>
			<key>match</key>
			<string>(//).*</string>
			<key>name</key>
			<string>comment.line.double-slash.swift</string>
		</dict>
		<key>increment-decrement-operator</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)(\+\+|\-\-)(?!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)</string>
			<key>name</key>
			<string>keyword.operator.increment-or-decrement.swift</string>
		</dict>
		<key>literals</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string-literal</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#special-literal</string>
				</dict>
			</array>
		</dict>
		<key>logical-operator</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)(!|&amp;&amp;|\|\|)(?!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)</string>
			<key>name</key>
			<string>keyword.operator.logical.swift</string>
		</dict>
		<key>loop-control</key>
		<dict>
			<key>match</key>
			<string>\b(while|do|for|in)\b</string>
			<key>name</key>
			<string>keyword.control.loop.swift</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>(?:[\-+])?\d+(?:\.\d+)?\b</string>
			<key>name</key>
			<string>constant.numeric.swift</string>
		</dict>
		<key>operator-keywords</key>
		<dict>
			<key>match</key>
			<string>\b(operator|prefix|infix|postfix)\b</string>
			<key>name</key>
			<string>storage.type.swift</string>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comparative-operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#assignment-operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#logical-operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#remainder-operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#increment-decrement-operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#overflow-operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#range-operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#bitwise-operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#arithmetic-operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#ternary-operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#custom-operator</string>
				</dict>
			</array>
		</dict>
		<key>overflow-operator</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)\&amp;(\+|\-|\*|\/|%)(?!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)</string>
			<key>name</key>
			<string>keyword.operator.overflow.swift</string>
		</dict>
		<key>primitive-type</key>
		<dict>
			<key>comment</key>
			<string>Primitive types</string>
			<key>match</key>
			<string>\b(Int|Float|Double|String|Bool|Character)\b</string>
			<key>name</key>
			<string>storage.type.swift</string>
		</dict>
		<key>range-operator</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)\.\.(?:\.)?(?!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)</string>
			<key>name</key>
			<string>keyword.operator.range.swift</string>
		</dict>
		<key>remainder-operator</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)\%(?!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)</string>
			<key>name</key>
			<string>keyword.operator.remainder.swift</string>
		</dict>
		<key>special-keyword</key>
		<dict>
			<key>match</key>
			<string>\b(self|super)\b</string>
			<key>name</key>
			<string>constant.language.swift</string>
		</dict>
		<key>special-literal</key>
		<dict>
			<key>match</key>
			<string>\b__(FILE|LINE|COLUMN|FUNCTION)__\b</string>
			<key>name</key>
			<string>keyword.other.literal.swift</string>
		</dict>
		<key>storage-type</key>
		<dict>
			<key>match</key>
			<string>\b(var|func|let|class|enum|struct|protocol|extension|typealias)\b</string>
			<key>name</key>
			<string>storage.type.swift</string>
		</dict>
		<key>string-literal</key>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.swift</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\([0tnr\"\'\\]|x\h{2}|u\h{4}|U\h{8})</string>
					<key>name</key>
					<string>constant.character.escape.swift</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\\\(</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.expression.begin.swift</string>
						</dict>
					</dict>
					<key>contentName</key>
					<string>meta.expression.swift</string>
					<key>end</key>
					<string>\)</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.expression.end.swift</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>(\"|\\)</string>
					<key>name</key>
					<string>invalid.illegal.swift</string>
				</dict>
			</array>
		</dict>
		<key>switch-statement</key>
		<dict>
			<key>match</key>
			<string>\b(switch|case|default|where)\b</string>
			<key>name</key>
			<string>keyword.control.conditional.swift</string>
		</dict>
		<key>ternary-operator</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=[\s(\[{,;:])(\?|:)(?=[\s)\]},;:])</string>
			<key>name</key>
			<string>keyword.operator.ternary.swift</string>
		</dict>
		<key>type-casting-operator</key>
		<dict>
			<key>match</key>
			<string>\b(is|as)\b</string>
			<key>name</key>
			<string>keyword.operator.cast.swift</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.swift</string>
	<key>uuid</key>
	<string>7efa1168-97c3-4433-8dd7-15b99bf3bb53</string>
</dict>
</plist>
