<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>swift</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>Swift</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#literals</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#loop-control</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#conditional-statement</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#control-transfer-statement</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator-keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#special-keyword</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class-function</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#primitive-type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#collection-type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#optional-type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#protocol-composition-type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storage-type</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#boolean</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#import</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>arithmetic-operator</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)(\+|\-|\*|\/)(?!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)</string>
			<key>name</key>
			<string>keyword.operator.arithmetic.swift</string>
		</dict>
		<key>array-type</key>
		<dict>
			<key>begin</key>
			<string>\b(Array)(&lt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.array.swift</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.array.begin.swift</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.array.end.swift</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.array.swift</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>assignment-operator</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)(\+|\-|\*|\/|%|&lt;&lt;|&gt;&gt;|&amp;|\^|\||&amp;&amp;|\|\|)?=(?!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)</string>
			<key>name</key>
			<string>keyword.operator.assignment.swift</string>
		</dict>
		<key>bitwise-operator</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)(&amp;|\||\^|&lt;&lt;|&gt;&gt;)(?!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)</string>
			<key>name</key>
			<string>keyword.operator.bitwise.swift</string>
		</dict>
		<key>block-comment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.block.begin.swift</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Block level comments</string>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.block.end.swift</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.swift</string>
		</dict>
		<key>boolean</key>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>keyword.constant.boolean.swift</string>
		</dict>
		<key>class-function</key>
		<dict>
			<key>match</key>
			<string>\b(init|get|set|willSet|didSet|override)</string>
			<key>name</key>
			<string>keyword.swift</string>
		</dict>
		<key>collection-type</key>
		<dict>
			<key>comment</key>
			<string>Collection types</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#array-type</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#dictionary-type</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Array|Dictionary)\b</string>
					<key>name</key>
					<string>support.type.swift</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>comment</key>
			<string>All comment types</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#documentation-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#block-comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#in-line-comment</string>
				</dict>
			</array>
		</dict>
		<key>comparative-operator</key>
		<dict>
			<key>match</key>
			<string>(?&lt;!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)((=|!)==?|(&lt;|&gt;)=?|~=)(?!\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)</string>
			<key>name</key>
			<string>keyword.operator.comparative.swift</string>
		</dict>
		<key>conditional-statement</key>
		<dict>
			<key>name</key>
			<string>keyword.control.conditional.swift</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#if-else-statement</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#switch-statement</string>
				</dict>
			</array>
		</dict>
		<key>control-transfer-statement</key>
		<dict>
			<key>match</key>
			<string>\b(continue|break|fallthrough|return)\b</string>
			<key>name</key>
			<string>keyword.control.transfer.swift</string>
		</dict>
		<key>custom-operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=[\s(\[{,;:])(\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)++(?![\s)\]},;:])</string>
					<key>name</key>
					<string>keyword.operator.custom.prefix.unary.swift</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;![\s(\[{,;:])(\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)++(?![\s)\]},;:\.])</string>
					<key>name</key>
					<string>keyword.operator.custom.postfix.unary.swift</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=[\s(\[{,;:])(\/|=|\-|\+|!|\*|%|&lt;|&gt;|&amp;|\||\^|~|\.)++(?=[\s)\]},;:])</string>
					<key>name</key>
					<string>keyword.operator.custom.binary.swift</string>
				</dict>
			</array>
		</dict>
		<key>dictionary-type</key>
		<dict>
			<key>begin</key>
			<string>\b(Dictionary)(&lt;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.dictionary.swift</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.dictionary.begin.swift</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.dictionary.end.swift</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.dictionary.swift</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>documentation-comment</key>
		<dict>
			<key>begin</key>
			<string>/\*\*</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.block.documentation.begin.swift</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Documentation comments</string>
			<key>end</key>
			<string>\*/</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.block.documentation.end.swift</string>
				</dict>
			</dict>
			<key>name</key>
			<string>comment.block.documentation.swift</string>
		</dict>
		<key>floating-point-literal</key>
		<dict>
			<key>name</key>
			<string>constant.numeric.floating-point.swift</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
